zenn previewでローカルに配置した画像のプレビューとバリデーションに対応
zenn-dev/zenn-editor pull request #194
Opened 2021-07-15 03:07 UTC by cm-igarashi-ryosuke

## :bookmark_tabs: Summary
zenn previewでローカルに配置した画像のプレビューとバリデーションに対応

Resolves: https://github.com/zenn-dev/zenn-community/issues/72

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [ ] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-editor/blob/main/docs/CONTRIBUTING.md) を読んだ
- [ ] :label: プルリクエストにラベルが付与されている
- [ ] :woman_technologist: `canary` ブランチに対するプルリクエストである

2021-07-15 03:15 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/lib/articles.ts
> +  const errors = validateHtml(bodyHtml);
client側でhtmlを解析する軽量なライブラリがないため、server側で検証してerrorsを含めて返すようにしました。

2021-07-15 03:17 UTC, cm-igarashi-ryosuke commented
## エラーメッセージ

![image](https://user-images.githubusercontent.com/13619209/125723652-b4df7f88-9367-4812-9c11-3cbfcfd88f7d.png)

## プレビュー

![image](https://user-images.githubusercontent.com/13619209/125723679-7764caf2-054c-482f-ad8b-f24129f7d0da.png)

相対パスでもプレビューには表示されてしまう。

2021-07-15 07:03 UTC, catnose99 commented on packages/zenn-cli/src/server/lib/articles.ts
> +  const errors = validateHtml(bodyHtml);
良いですね。もともとそうするべきでした

2021-07-15 07:27 UTC, catnose99 commented on packages/zenn-cli/src/server/lib/validator.ts
> +          message: `不正な画像のパスが検出されました: '${src}'. ローカルの画像を指定する場合は、パスを '/images/*' で指定してください。`,
プレビューでは問題なく表示されてしまうので、zenn.devへのデプロイした際にうまく表示されないことを説明した方が分かりやすいかなと思いました。

例えば以下のようなメッセージとか？（少し長くなってしまいますが…）
```
ローカルの画像を相対パスで参照するとzenn.devへデプロイされたときに表示できません。
'/images/example.png'のように'/images/'から始まるパスを指定してください。
```

2021-07-15 07:37 UTC, catnose99 commented on packages/zenn-cli/src/server/preview/app.ts
> +  });
```
import { getWorkingPath } from '../lib/helper';

app.get('/images/*', (req, res) => {
    res.sendFile(getWorkingPath(req.path));
 });
```

とすれば`images`ディレクトリの中身を参照できるはずです。`articles/*`や`books/*`も`getWorkingPath`を使って参照しています。

2021-07-15 07:37 UTC, bisque33 commented on packages/zenn-cli/src/server/lib/validator.ts
> +          message: `不正な画像のパスが検出されました: '${src}'. ローカルの画像を指定する場合は、パスを '/images/*' で指定してください。`,
@catnose99 やっぱり分かりにくいですよね。デプロイされた時に無効になる画像はプレビューに表示されないようにsrcを書き換えしまいましょうか？そこまでやろうか迷ったんですが、プレビューはzennにデプロイ後の状態を表示したいので、その方がいいかもしれない。

2021-07-15 07:38 UTC, catnose99 requested changes
素晴らしいです！
いくつか確認をお願いします！

2021-07-15 07:51 UTC, catnose99 commented on packages/zenn-cli/src/server/lib/validator.ts
> +          message: `不正な画像のパスが検出されました: '${src}'. ローカルの画像を指定する場合は、パスを '/images/*' で指定してください。`,
たしかに…
もしやるならcheerioで未対応の画像パスを検出したときに、そのimg要素をエラーメッセージを含む要素に置き換えるイメージが良いですかね。

```html
<!-- オリジナルのhtml -->
<img src="../images/example.png" />
```
👇 プレビュー時に置換
```html
<!-- オリジナルのhtml -->
<p style="color: var(--c-error); font-weight: 700">
<code>../images/example.png</code>を表示できません。ローカルの画像を読み込むには相対パスではなく<code>/images/example.png</code>のように<code>/images/</code>から始まるパスを指定してください。
</p>
```

エラーメッセージの文字色となるのでプレビュー時にすぐ気づくはずです。
開発側の都合ですが、このimgの置換と、バリデーションのエラーメッセージをそれぞれ表示するようにするとややこしくなりそうですね。例えばsvg画像に対応したときにどちらかの追従を忘れそう。
imgの置換だけでも良いのかもしれない？

2021-07-15 09:23 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/preview/app.ts
> +  });
できました！

2021-07-15 09:24 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/lib/articles.ts
> +  const errors = validateHtml(bodyHtml);
ValidationError を使わないようにしたので、ここも戻しました。

2021-07-15 09:27 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/lib/validator.ts
> +          message: `不正な画像のパスが検出されました: '${src}'. ローカルの画像を指定する場合は、パスを '/images/*' で指定してください。`,
@catnose99 バリデーションエラー部分には表示せず、プレビュー内にエラーメッセージを表示するようにしました。どうでしょうか？もらったHTMLをそのまんま貼りましたが良かったでしょうか？
![image](https://user-images.githubusercontent.com/13619209/125764319-b6cfef7d-862e-4dd1-a406-9ae2f036b725.png)

2021-07-16 01:53 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/client/components/Sidebar.tsx
> +                hash="cli-%E3%81%A7%E7%94%BB%E5%83%8F%E3%82%92%E7%AE%A1%E7%90%86%E3%81%99%E3%82%8B"
実際の記事はbackendをデプロイしてからデプロイします。

2021-07-16 06:34 UTC, catnose99 commented on packages/zenn-cli/src/server/lib/validator.ts
> +          message: `不正な画像のパスが検出されました: '${src}'. ローカルの画像を指定する場合は、パスを '/images/*' で指定してください。`,
いいと思います！（あとでこちらで微調整するかも？）

2021-07-16 06:34 UTC, catnose99 commented on packages/zenn-cli/src/client/components/Sidebar.tsx
> +                hash="cli-%E3%81%A7%E7%94%BB%E5%83%8F%E3%82%92%E7%AE%A1%E7%90%86%E3%81%99%E3%82%8B"
おけまる〜

2021-07-16 06:36 UTC, catnose99 approved these changes
🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌

2021-07-16 06:38 UTC, merged