画像ファイルの存在確認とファイルサイズの検証を追加
zenn-dev/zenn-editor pull request #201
Opened 2021-08-03 08:39 UTC by cm-igarashi-ryosuke

## :bookmark_tabs: Summary
zenn previewにて、画像ファイルの存在確認とファイルサイズの検証を追加しました。

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-editor/blob/main/docs/CONTRIBUTING.md) を読んだ
- [x] :label: プルリクエストにラベルが付与されている
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである

2021-08-03 08:40 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/lib/helper.ts
> +      );
ファイルが存在しない場合のエラーメッセージ

![スクリーンショット 2021-08-03 17 36 13](https://user-images.githubusercontent.com/13619209/127985359-5d40cd56-f075-4752-b9b9-d3af402d4375.png)

2021-08-03 08:40 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/lib/helper.ts
> +      );
ファイルサイズが大きい場合のエラーメッセージ

![image](https://user-images.githubusercontent.com/13619209/127985455-a0626b94-3ce0-4f1a-81b4-7eeba4d69028.png)

2021-08-03 08:51 UTC, cm-wada-yusuke requested changes
対応ありがとうございます、お手数ですが１点確認お願いします :pray:

2021-08-03 08:51 UTC, cm-wada-yusuke commented on packages/zenn-cli/src/server/lib/helper.ts
> +      );
[imo] 実際のファイルサイズを出してあげてもいいかな？というのと、Bookカバーのメガバイト計算とちょっと違うのでどちらかを合わせたほうが良さそうです。

packages/zenn-cli/src/client/lib/validator.ts

2021-08-03 09:04 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/lib/helper.ts
> +      );
おおお鋭い。ありがとうございます！

> 実際のファイルサイズを出してあげてもいいかな？
確かに！そうします！

> というのと、Bookカバーのメガバイト計算とちょっと違うのでどちらかを合わせたほうが良さそうです。
確かに！サーバの方も1000で計算している場所と、1024で計算している場所があるので、1024の方に統一したいと思います。

2021-08-04 04:49 UTC, cm-igarashi-ryosuke commented on packages/zenn-cli/src/server/lib/helper.ts
> +      );
対応しました！

![image](https://user-images.githubusercontent.com/13619209/128123773-f2ae323a-b04b-46aa-854b-f6b36f6df450.png)

2021-08-04 07:38 UTC, cm-wada-yusuke approved these changes
LGTM!!

2021-08-04 07:44 UTC, merged