feat: 印刷時にdetailsを開くようにした
zenn-dev/zenn-editor pull request #280
Opened 2022-03-24 08:54 UTC by uttk-dev

## :bookmark_tabs: Summary

印刷時に details を開くように修正しました。

Resolves #267 

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-editor/blob/main/CONTRIBUTING.md) を読んだ
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである

2022-03-25 00:59 UTC, catnose99 requested changes
ありがとうございます！ いい感じだと思います！！
本のチャプターでも同じ挙動にしたいので、カスタムフックとして切り出すのが良いかもです

2022-03-27 22:40 UTC, uttk-dev commented on packages/zenn-cli/src/client/components/PrintDetailsOpener.tsx
> +};
コンポーネントとして実装することで、実装箇所を少なくしました。

2022-03-27 22:41 UTC, uttk-dev commented on packages/zenn-cli/src/client/components/BodyContent.tsx
> +      </PrintDetailsOpener>
機能をコンポーネントとして実装することで、影響範囲の可視化と実装箇所を削減するように修正しました。

2022-03-28 01:32 UTC, catnose99 approved these changes
素晴らしい〜〜〜〜
LGTMです！

2022-03-28 01:32 UTC, merged