new:article に --publication-name オプションを追加
zenn-dev/zenn-editor pull request #373
Opened 2022-09-20 06:16 UTC by kokuyouwind

## :bookmark_tabs: Summary

記事作成後に都度 publication_name を埋めるのは面倒なので、コマンドオプションで指定できるようにしました。
(Issueでの議論を経ていませんが、小さな変更なので先にPRも立てています。)

Resolves #372

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-editor/blob/main/CONTRIBUTING.md) を読んだ
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである

2022-09-20 06:44 UTC, uttk-dev requested changes
ほとんどLGTMですが、一点だけコメントしました。
確認のほど、よろしくお願いします。

2022-09-20 06:44 UTC, uttk-dev commented on packages/zenn-cli/src/server/commands/new-article.ts
> +      publicationName !== '' ? `publication-name: ${publicationName}` : null,
タイトルと同じようにサニタイズしてもらえると、より安全になると思います。

```suggestion
      publicationName !== '' ? `publication-name: ${publicationName.replace(/"/g, '\\"')}` : null,
```

2022-09-20 08:04 UTC, kokuyouwind commented on packages/zenn-cli/src/server/commands/new-article.ts
> +      publicationName !== '' ? `publication-name: ${publicationName}` : null,
入力サニタイズしていたんですね、見逃していました。
コミット取り込みました、ありがとうございます:pray: https://github.com/zenn-dev/zenn-editor/pull/373/commits/af0b62a23b56e24a1923bd15d2630c4f6d14a863

2022-09-21 03:12 UTC, uttk-dev requested changes
すいません！動作確認していて気が付いたんですが、`zenn new:article --help` を実行した時のメッセージに `--publication-name` の説明が抜けていました。簡単にでもいいので、追加して頂けると助かります🙏

https://github.com/zenn-dev/zenn-editor/blob/83f59eac7e016919edad4a4d4dc623241ded9a4d/packages/zenn-cli/src/server/lib/messages.ts#L55-L77

2022-09-21 06:32 UTC, kokuyouwind commented
@uttk-dev 

> すいません！動作確認していて気が付いたんですが、zenn new:article --help を実行した時のメッセージに --publication-name の説明が抜けていました。簡単にでもいいので、追加して頂けると助かります🙏

ヘルプメッセージ失念してました、ありがとうございます！
https://github.com/zenn-dev/zenn-editor/pull/373/commits/1c879a31d697537878fb5efb5fcca346f3135058 で追加したのでご確認お願いします:pray:

2022-09-21 08:09 UTC, uttk-dev approved these changes
LGTMです！対応ありがとうございました！

2022-09-21 08:12 UTC, merged