埋め込みコンテンツに関するドキュメントを最新の内容に
zenn-dev/zenn-editor pull request #378
Opened 2022-09-29 08:14 UTC by catnose99

## :bookmark_tabs: Summary

### :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-editor/blob/main/CONTRIBUTING.md) を読んだ
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである

2022-09-29 08:16 UTC, catnose99 commented on README.md
> -- Yusuke Wada ([@cm-wada-yusuke](https://github.com/cm-wada-yusuke))
コントリビュートしてくれた人数が増えてきたため削除します！
（ https://github.com/zenn-dev/zenn-editor/graphs/contributors を見てもらう）

2022-09-29 08:26 UTC, cm-wada-yusuke commented on README.md
> +以下のようにMarkdownをHTMLに変換します。
```suggestion
以下のようにMarkdownをHTMLに変換します。この処理は、Node.jsでのみ実行できます。ブラウザで実行するとエラーになりますのでご注意ください。
```

下がHTMLの記述になっているので実行環境を明示したほうが良さそうだと思いました。

2022-09-29 22:43 UTC, uttk-dev commented on README.md
> +以下のようにMarkdownをHTMLに変換します。
フロント側でやってエラーになる！みたいな issue 立てられたことあるので、実行環境の明示はやっておいた方がよさそうですね！

2022-09-29 23:21 UTC, uttk-dev requested changes
ほとんどLGTMです！ありがとうございます！！！！
いくつかコメントしたので、確認お願いします🙇‍♂️

2022-09-29 23:21 UTC, uttk-dev commented on README.md
>  ```
zenn-embed-elements の記述と合わせた方がよさそうに思いました。

```tsx
// Reactで使う場合
export default function App(...) {
  useEffect(()=> {
    import("zenn-embed-elements")
  },[])
}
```

2022-09-29 23:21 UTC, uttk-dev commented on README.md
>  ```
より実行順をわかりやすくするために、html 描画部分の処理も書いた方がよさそうに思いましたが、混乱させちゃいそうな気もするので、対応はお任せします。

```tsx
// React で使う場合
export default function App(props) {

  useEffect(()=> {
    import("zenn-embed-elements")
  },[])

  return (
    <div 
      className="znc"
      dangerouslySetInnerHTML={{
        __html: html // markdownから変換された html 文字列を表示
      }}
    />
  )
}
```

2022-09-29 23:21 UTC, uttk-dev commented on packages/zenn-embed-elements/README.md
> +}
TypeScript を使っている場合、返り値の型がエラーになるので、アロー関数の `{ }` を省略せず書いた方が混乱を避けやすいかなと思います。

```suggestion
export default function App(...) {
  useEffect(() => {
    import("zenn-embed-elements")
  },[])
}
```

参考：
<img width="399" alt="image" src="https://user-images.githubusercontent.com/97154037/193158700-decedfad-011a-4667-af9e-0ea588040210.png">

2022-10-04 23:13 UTC, catnose99 commented on README.md
> +以下のようにMarkdownをHTMLに変換します。
素晴らしい案！

2022-10-04 23:15 UTC, catnose99 commented on README.md
>  ```
そうします！

2022-10-04 23:15 UTC, catnose99 commented on packages/zenn-embed-elements/README.md
> +}
ありがとうございます。修正します！

2022-10-04 23:36 UTC, uttk-dev approved these changes
LGTMです！

2022-10-04 23:36 UTC, merged