docs: LICENSE ファイルの追加と README 内の表現を修正
zenn-dev/zenn-editor pull request #435
Opened 2023-02-21 08:54 UTC by uttk-dev

## :bookmark_tabs: Summary

- LICENSE ファイルをルートと各パッケージのディレクトリに追加
- README 内の表現がライブラリの意図と合わない可能性があるので修正

## :clipboard: Tasks

プルリクエストを作成いただく際、お手数ですが以下の内容についてご確認をお願いします。

- [x] :book: [Contribution Guide](https://github.com/zenn-dev/zenn-editor/blob/main/CONTRIBUTING.md) を読んだ
- [x] :woman_technologist: `canary` ブランチに対するプルリクエストである
- [x] zenn-cli で実行して正しく動作しているか確認する
- [x] 不要なコードが含まれていないか( コメントやログの消し忘れに注意 )
- [x] XSS になるようなコードが含まれていないか
- [x] モバイル端末での表示が考慮されているか
- [x] Pull Reuqest の内容は妥当か( 膨らみすぎてないか )

より詳しい内容は [Pull Request Policy](https://github.com/zenn-dev/zenn-editor/tree/canary/docs/pull_request_policy.md) を参照してください。

2023-02-21 09:10 UTC, cm-igarashi-ryosuke requested changes
よさそうです！✨
１点だけリクエストしました！

2023-02-21 09:10 UTC, cm-igarashi-ryosuke commented on README.md
> +このリポジトリは、主に Zenn の Markdown に関するパッケージをまとめて管理しています。
（公開している意図を示すために以下を追加して欲しいです）

これらのパッケージを利用することで、[Zenn CLI](https://zenn.dev/zenn/articles/install-zenn-cli) やZennの[VSCode拡張](https://marketplace.visualstudio.com/items?itemName=zenn.zenn-preview)のような周辺システムを作ることができます。

2023-02-21 09:26 UTC, uttk-dev commented on README.md
> +このリポジトリは、主に Zenn の Markdown に関するパッケージをまとめて管理しています。
修正しました。

2023-02-21 09:27 UTC, merged

2023-04-02 08:31 UTC, xlove168 approved these changes